const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const path = require('path');
const os = require('os');

const app = express();
const server = http.createServer(app);
// tldraw snapshots (sent by phones and laptops) can exceed socket.io's 1 MB
// default; an oversized message makes the server drop the connection.
const io = new Server(server, { maxHttpBufferSize: 50e6 });

/* ── LAN IP detection ─────────────────────────────────────────────────────── */
function getLanIp() {
  const ifaces = os.networkInterfaces();
  for (const name of Object.keys(ifaces)) {
    for (const iface of ifaces[name]) {
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address;
      }
    }
  }
  return null;
}

// In-memory rate limiter: 120 HTTP requests per IP per minute across all routes
const httpRateMap = new Map();
function rateLimit(req, res, next) {
  const ip  = req.ip || (req.socket && req.socket.remoteAddress) || 'unknown';
  const now = Date.now();
  const entry = httpRateMap.get(ip) || { count: 0, resetAt: now + 60_000 };
  if (now > entry.resetAt) { entry.count = 0; entry.resetAt = now + 60_000; }
  entry.count++;
  httpRateMap.set(ip, entry);
  if (entry.count > 120) {
    return res.status(429).send('Too Many Requests');
  }
  next();
}
app.use(rateLimit);

// Serve the phone PWA index for both /phone and /phone/
app.get(['/phone', '/phone/'], rateLimit, (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'phone', 'index.html'));
});

// Serve other phone static assets (/phone/css, /phone/js, /phone/manifest.json, etc.)
app.use('/phone', express.static(path.join(__dirname, 'public', 'phone')));

// Serve remaining static files from public/
app.use(express.static(path.join(__dirname, 'public')));

// 8th Wall engine (xr.js loads its xr-slam.js chunk from the same folder)
app.use('/vendor/xr8', express.static(path.join(__dirname, 'node_modules', '@8thwall', 'engine-binary', 'dist')));

/* ── 8th Wall image targets for the phone tracking border ──────────────────
 * Generated on demand for each phone screen size (CSS px), e.g.
 *   /xr8-targets/390x844/targets.json            → [topTarget, bottomTarget]
 *   /xr8-targets/390x844/border-top_luminance.png
 */
const { renderTargets } = require('./tools/imageTarget');
const targetCache = new Map(); // "WxH" → renderTargets() result
function getTargets(size) {
  const m = /^(\d{3,4})x(\d{3,4})$/.exec(size);
  if (!m) return null;
  const w = Number(m[1]), h = Number(m[2]);
  if (w < 200 || h < 200 || w > 2000 || h > 3000) return null;
  const key = w + 'x' + h;
  if (!targetCache.has(key)) {
    if (targetCache.size > 50) targetCache.clear();
    targetCache.set(key, renderTargets(w, h, { baseUrl: `/xr8-targets/${key}/` }));
  }
  return targetCache.get(key);
}
app.get('/xr8-targets/:size/targets.json', (req, res) => {
  const targets = getTargets(req.params.size);
  if (!targets) return res.status(400).send('size must be WIDTHxHEIGHT in CSS px');
  res.json(targets.map((t) => t.json));
});
app.get('/xr8-targets/:size/:file', (req, res) => {
  const targets = getTargets(req.params.size);
  const t = targets && targets.find((x) => x.luminanceFile === req.params.file);
  if (!t) return res.status(404).send('not found');
  res.type('png').set('Cache-Control', 'public, max-age=86400').send(t.luminancePng);
});

/* ── Config endpoint — exposes the LAN phone URL ──────────────────────────── */
app.get('/api/config', (req, res) => {
  const lanIp   = getLanIp();
  const port    = process.env.PORT || 3000;
  const phoneUrl = lanIp ? `http://${lanIp}:${port}/phone` : null;
  res.json({ phoneUrl });
});

// All devices share one session — no room codes required.
// Any connecting socket is a participant; laptops and phones find each other automatically.
const ROOM = 'main';

// Latest tldraw full-state snapshot — sent to devices that join mid-session.
let tldrawSnapshot = null;

// Per-clientId marker assignment — persists across page refreshes so the same
// physical phone always gets the same marker ID.
// clientId is a UUID generated by the phone and stored in localStorage.
const clientMarkers = new Map(); // clientId → markerId
const socketMeta = new Map();    // socketId → { type, markerId }
let nextMarkerId = 0;

function assignMarkerId(clientId) {
  if (clientMarkers.has(clientId)) return clientMarkers.get(clientId);
  const id = nextMarkerId++;
  clientMarkers.set(clientId, id);
  return id;
}

io.on('connection', (socket) => {
  let myType   = null;
  let myMarkerId = null;

  socket.on('device:register', ({ type, clientId }) => {
    myType = type;
    socket.join(ROOM);

    // Assign a stable markerId for phones (persisted by clientId)
    if (type === 'phone') {
      myMarkerId = assignMarkerId(clientId || socket.id);
      // Acknowledge with the assigned markerId
      socket.emit('device:registered', { markerId: myMarkerId, socketId: socket.id });
    } else {
      socket.emit('device:registered', { socketId: socket.id });
    }

    socketMeta.set(socket.id, { type, markerId: myMarkerId });

    // Notify others that a new device joined
    socket.to(ROOM).emit('device:status', {
      type,
      connected: true,
      markerId: myMarkerId,
      socketId: socket.id
    });

    // Tell the newcomer about every device already in the room
    const roomSockets = io.sockets.adapter.rooms.get(ROOM);
    if (roomSockets && roomSockets.size > 1) {
      roomSockets.forEach((sid) => {
        if (sid === socket.id) return;
        const meta = socketMeta.get(sid);
        if (!meta) return;
        socket.emit('device:status', {
          type: meta.type,
          connected: true,
          markerId: meta.markerId,
          socketId: sid
        });
      });
    }
  });

  socket.on('phone:touch',    (data) => { socket.to(ROOM).emit('phone:touch',    data); });
  socket.on('phone:viewport', (data) => { socket.to(ROOM).emit('phone:viewport', data); });
  socket.on('laptop:state',  (data) => { socket.to(ROOM).emit('laptop:state',  data); });
  socket.on('config:change', (data) => { socket.to(ROOM).emit('config:change', data); });
  socket.on('webrtc:signal', (data) => {
    if (data && data.to) {
      io.to(data.to).emit('webrtc:signal', Object.assign({}, data, { from: socket.id }));
      return;
    }
    socket.to(ROOM).emit('webrtc:signal', Object.assign({}, data, { from: socket.id }));
  });
  socket.on('webrtc:ready',   (data) => { socket.to(ROOM).emit('webrtc:ready', data); });
  // 8th Wall border tracking test page (/xr8-test.html ↔ /phone/border-test.html)
  socket.on('xr8test:mode',   (data) => { socket.to(ROOM).emit('xr8test:mode', data); });
  socket.on('xr8test:hello',  (data) => { socket.to(ROOM).emit('xr8test:hello', data); });
  socket.on('webrtc:stream-state', (data) => { socket.to(ROOM).emit('webrtc:stream-state', data); });

  // ── tldraw real-time sync ─────────────────────────────────────────────────
  // Incremental diff — relay immediately to all other room members.
  socket.on('tldraw:diff',     (diff)     => { socket.to(ROOM).emit('tldraw:diff', diff); });
  // Full snapshot — store server-side so late joiners can catch up.
  socket.on('tldraw:snapshot', (snapshot) => { tldrawSnapshot = snapshot; });
  // New client requests the current full state.
  socket.on('tldraw:init-request', () => {
    if (tldrawSnapshot) socket.emit('tldraw:snapshot', tldrawSnapshot);
  });

  socket.on('disconnect', () => {
    if (myType) {
      socket.to(ROOM).emit('device:status', {
        type: myType,
        connected: false,
        markerId: myMarkerId,
        socketId: socket.id
      });
    }
    socketMeta.delete(socket.id);
  });
});

const PORT = process.env.PORT || 3000;
server.listen(PORT, () => {
  console.log(`ReverseProjection server running at http://localhost:${PORT}`);
});
